### PR TITLE
Updated error message to include email address.

### PR DESCRIPTION
**Pull request by markjamesbutler**
Quick fix to add identity dev email address as contact point.

### CODE REVIEW

**Comment by susiecoleman** [comment]
Looks fine to me but isn't up to date with master....

**Comment by susiecoleman** [comment]
Last commit has broken a test

**Comment by susiecoleman** [comment]
:+1: but needs master merging in again first

**Comment by emma-p** [comment]
:+1: Make sure to update the confs on CODE & PROD before merging

**Pull request merged**
