### PR TITLE
Add frontend routes for perma-banning email addresses

### PR DESCRIPTION
**Pull request by rahilb**
Adds a button to make a reserved email record permanent, relates to https://github.com/guardian/identity-platform/pull/240

### CODE REVIEW

**Comment by jfsoul** [comment]
Do we need to think about the labels on the edit page in this as well? Add one for permanently banned state?

**Comment by rahilb** [comment]
I think this is ready to go, once the prod schema has been migrated. 

Here's some screenshots, I've from CODE: 

screen shot 2018-06-15 at 16 18 44
screen shot 2018-06-15 at 16 42 04
screen shot 2018-06-15 at 16 42 14
screen shot 2018-06-15 at 16 42 30

**Comment by jfsoul** [comment]
Minor: maybe use a different logo for the new button? A warning symbol, or a hand or a locked lock.

**Comment by rahilb** [comment]
I actually changed it already, just forgot to update the screenshot. Unreserve is now a trash icon and blocklist is a padlock.

**Pull request merged**
